### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path

### ISSUE THREAD

**Issue by HomerBeer** [lingarr-translate/lingarr#14]
Looks very promising!

But after the latest version install, it can not found the correct paths anymore.
Set Sonarr configs, the shows appears. 

But then i get this error:
System.IO.DirectoryNotFoundException: Could not find a part of the path

**Comment by rowanfuchs** [comment]
The shows, seasons, and episodes are imported via Sonarr's api, whereas the subtitles are collected via scanning the mapped volumes. Did you map your tv volume correctly?
You have to replace "/path/to/tv" fully with the path you also use in Sonarr or your media application:
`- /path/to/tv:/app/media/tv`

If you have a little more logging, I can give a more exact answer, but with this, I assume the volume mapping is incorrect.

**Comment by HomerBeer** [comment]
I have, and it worked in the first version.

But know i get this:

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN6PGDACN79A", Request id "0HN6PGDACN79A:0000000D": An unhandled exception was thrown by the application.
      System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/media/Media/Series/1923 (2022) {imdb-tt18335752}/Season 1'.
         at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
         at System.IO.Enumeration.FileSystemEnumerator`1.Init()
         at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
         at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
         at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
         at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
         at Lingarr.Server.Services.SubtitleService.<>c__DisplayClass0_0.<Collect>b__1() in /src/Lingarr.Server/Services/SubtitleService.cs:line 18
         at System.Threading.Tasks.Task`1.InnerInvoke()
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Lingarr.Server.Services.SubtitleService.Collect(String path) in /src/Lingarr.Server/Services/SubtitleService.cs:line 18
         at Lingarr.Server.Controllers.SubtitleController.Collect(String path) in /src/Lingarr.Server/Controllers/SubtitleController.cs:line 27
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]

**Comment by rowanfuchs** [comment]
`media/Media/` media is mentioned twice, are you sure that is correct? i.e. my setup is as following:

``
volumes:
  - /mnt/hdd/media/movies:/app/media/movies
  - /mnt/hdd/media/tvshows:/app/media/tv
``

**Comment by HomerBeer** [comment]
Aah, thanx.. i was don't aware of that. 
Found that strange to.

 volumes:
      - /volume1/Media:/app/media/tv
    
I use these in my sonarr to.

**Comment by rowanfuchs** [comment]
This looks correct, had the problem been resolved or is this mapping causing the issue?

**Comment by HomerBeer** [comment]
I changed nothing, this is correct. The problem is still there.

**Comment by rowanfuchs** [comment]
That's really odd. I agree that it's correct, and it should work. Luckily i've been able to replicate the issue, which is great. I have been working on a new release that should have come out today or one of these days, so I will try to fix the issue there.

**Comment by rowanfuchs** [comment]
I had to correct my previous reply as on a different system I seemed to have the same result however by adding `./` to the mapping folder making it a relative path it resolved it for me.

i.e. changing `- /volume1/Media/Series:/app/media/tv` to `- ./volume1/Media/Series:/app/media/tv`

Another thing we could try is a named volume but before doing that, are you starting the docker-compose the same way and on the same location that you have started sonarr?

```yaml
volumes:
  - tv_series:/app/media/tv

volumes:
  tv_series:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/Media/Series
```

**Comment by HomerBeer** [comment]
When i changed it to  ./volume1/Media/Series:/app/media/tv, it says that it don't exist.

Yes, i use portainer on my Synology container manager. Same location.
Tried it, but stille the same issue.

**Comment by rowanfuchs** [comment]
Everything points to a invalid mapping, could you sh into the container and validate the folder structure? There shouldn't be any folders within the `/app` directory other than the `config` and `media` whereas media contains `movies` and `tv`

**Comment by HomerBeer** [comment]
Hmm, when i look in the /app directory there is config and media, what you say.. there are the movies and tv. When look in the tv directory, i see the shows.. so it mount correctly?

**Comment by rowanfuchs** [comment]
> Hmm, when i look in the /app directory there is config and media, what you say.. there are the movies and tv. When look in the tv directory, i see the shows.. so it mount correctly?

I see, sure looks like it indeed, and if you navigate to the series you tried to translate and enter `pwd` is the output similar to the path?

One other thing that came to my mind is the root folder path of sonar itself, I might have overlooked that one. Within sonarr's Settings->Media Management there is a root folder path configuration. Is it different than the Series folder you mentioned?

**Comment by HomerBeer** [comment]
I mount the Media folder in Sonarr. Then in Sonarr Media Management i selected the Media/Series folder.

**Comment by rowanfuchs** [comment]
Thank you very much for debugging with me, I was able to find the culprit. Both Sonarr and Radarr work with root folders which I didn't take into account, I will add them as soon as possible. I was about to release 0.8.5 with notifications this weekend but that can wait, I will include the fix of root folders.

**Comment by HomerBeer** [comment]
Super you found the problem. I try the fix when you release it.
Glad to help, i like this project!

**Comment by rowanfuchs** [comment]
Thank you! I hope we can get it to work and it will help out in your translation needs. I've added the needed changes (https://github.com/lingarr-translate/lingarr/commit/0ad250fa9fe3fe75f777257f2b82bf589016880b) I hope this will resolve the issue.

**Comment by HomerBeer** [comment]
I tried it, the movies works! But the shows still have the same error..

**Comment by rowanfuchs** [comment]
> I tried it, the movies works! But the shows still have the same error.. Hmm, some shows works.. strange..
> 
> Wait, i think i see it. I set sonarr to name the season maps "Season 01, Season 02 etc". When i changed the map in Season 1, it works.. is that correct?

Ah, I was afraid this was also an issue. You can rename them if you wish to use them for now, but I will change the way Lingarr handles seasons, that it follows Sonarr as Sonarr is the leading source.

I will give you an update when this is done, I'l probably include it in the automated translation update.

**Comment by HomerBeer** [comment]
Yeah, i renamed it for now. No problem. I'm glad i can use this ;)
Oh, btw.. the search function don't work correct.

**Comment by rowanfuchs** [comment]
My guess is that the synology has trouble supporting both services as they require quite some resources. I've fixed the season path with [Release 0.9.0](https://github.com/lingarr-translate/lingarr/releases/tag/0.9.0) and by that closing this issue. Thank you very much for your help and feedback.

**Comment by HomerBeer** [comment]
[Error] Microsoft.EntityFrameworkCore.Query: An exception occurred while iterating over the results of a query for context type 'Lingarr.Core.Data.LingarrDbContext'.

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: m.media_hash'.

Why this error?

**Comment by rowanfuchs** [comment]
Does this error remain when restarting the instance? media hash is used for automation,  v0.9.0 should have added them but it looks like they are missing in your media tables. If restarting doesn't work, the only option we have is reinstallation(remove the sqlite local.db fron the config folder), this sadly is annoying considering you need to reconfigure the settings but nothing else is lost.

**Comment by HomerBeer** [comment]
Yes' already did that.. but it dont show the movies and tv shows anymore.

   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: m.media_hash'.
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[2024-10-06 19:35:10] [Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN765JGDNDGE", Request id "0HN765JGDNDGE:00000021": An unhandled exception was thrown by the application.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: m.media_hash'.
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Lingarr.Server.Services.MediaService.GetMovies(String searchQuery, String orderBy, Boolean ascending, Int32 pageNumber, Int32 pageSize) in /src/Lingarr.Server/Services/MediaService.cs:line 48
   at Lingarr.Server.Controllers.MediaController.GetMovies(String searchQuery, String orderBy, Boolean ascending, Int32 pageSize, Int32 pageNumber) in /src/Lingarr.Server/Controllers/MediaController.cs:line 34
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Returning latest cached version: 0.9.0
[2024-10-06 19:35:33] [Error] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand (0ms) [Parameters=[@__p_1='?' (DbType = Int32), @__p_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT "m"."id", "m"."created_at", "m"."date_added", "m"."file_name", "m"."media_hash", "m"."path", "m"."radarr_id", "m"."title", "m"."updated_at"
FROM "movies" AS "m"
ORDER BY "m"."title", "m"."id"
LIMIT @__p_1 OFFSET @__p_0
[2024-10-06 19:35:33] [Error] Microsoft.EntityFrameworkCore.Query: An exception occurred while iterating over the results of a query for context type 'Lingarr.Core.Data.LingarrDbContext'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: m.media_hash'.
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: m.media_hash'.
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[2024-10-06 19:35:33] [Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN765JGDNDGE", Request id "0HN765JGDNDGE:00000028": An unhandled exception was thrown by the application.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: m.media_hash'.
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Lingarr.Server.Services.MediaService.GetMovies(String searchQuery, String orderBy, Boolean ascending, Int32 pageNumber, Int32 pageSize) in /src/Lingarr.Server/Services/MediaService.cs:line 48
   at Lingarr.Server.Controllers.MediaController.GetMovies(String searchQuery, String orderBy, Boolean ascending, Int32 pageSize, Int32 pageNumber) in /src/Lingarr.Server/Controllers/MediaController.cs:line 34
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by rowanfuchs** [comment]
Gotcha, I see what went wrong, I'l try to push out an update tonight!

**Comment by HomerBeer** [comment]
Yes, good job! But i'm sorry to say that the problem with te season path is still there..

**Comment by rowanfuchs** [comment]
Ouch, I did test that numerous ways, Sorry. My local path is even similair as yours `media\Series\A Discovery of Witches\Season 01` I've also set the format within Sonarr to `Season {season:00}` is there anything different in your setup? I might have missed something.

**Comment by HomerBeer** [comment]
Is het same that i use. But, can the series folder format become a problem?
I use:   {Series TitleYear} {imdb-{ImdbId}}

**Comment by HomerBeer** [comment]
Your welcome, graag gedaan! ;)

**Comment by HomerBeer** [comment]
Btw, is it possible to add more paths to the tv or movie path in the docker compose?
I use more paths then the series or films in Sonarr and Radarr.

**Comment by rowanfuchs** [comment]
Currently not, it used Sonarr and Radarr as a source. Did you manage to get something like that working with those services? Or is there a different reason their in a different folder does that work with your plex/emby/jellyfin?

**Comment by HomerBeer** [comment]
Yeah, i got the media folder mount in the sonarr and radarr services.  made different directory's and that work in Sonarr and Radarr. Then i can use those separately in my Plex server. Maybe i can mount only the media folder in lindarr, same as in my radarr, sonarr and plex?

**Comment by rowanfuchs** [comment]
Interesting setup, you might sharing some of your docker compose volume mappings? I will try to replicate it and considering the other request which arrived today I will have a look if I can find a nice solution.

One problem I see is that there is no good way of getting information about

**Comment by HomerBeer** [comment]
- /volume1/Media:/Media
is the only one i use in the docker composes. The subdirectory series, films etc i select in the services.

**Comment by rowanfuchs** [comment]
So within that Media folder you have a Movies, Series, and some other folders i.e. Series2, Movies2 e.t.c. Plex you map to /Media and it indexes it all?

**Comment by HomerBeer** [comment]
Maybe you can make in Lingarr that you can navigate trough the media folder and pick the directory's you need? Like in Sonarr, Radarr etc.

**Comment by rowanfuchs** [comment]
If you're interested, I've created a Discord; https://discord.gg/yThqvHw9Aq I will regularly release some test versions which I communicate there, hopefully we can tackle the mapping issues you and other people have.
