### ISSUE TITLE
Problem with mappings

### ISSUE THREAD

**Issue by YaibaToKen** [lingarr-translate/lingarr#30]
I'm running both Sonarr and Radarr as docker containers. 
Radarr uses `/home/dietpi/hdd4tb/Radarr/` mapped as `/media` while Sonarr uses `/home/dietpi/hdd4tb/Sonarr/` mapped as `/media`.
Those same paths are mapped as `/movies` and `/tv` in Lingarr's docker compose and the files show up inside the container.

I've tried setting up mappings in the settings, trying for example, with no success:
* Source: `/media` Target: `/tv` Media Type: Show
* Source: `/tv` Target: `/media` Media Type: Show
* Source: `/media` Target: `/movies` Media Type: Movie
* Source: `/movies` Target: `/media` Media Type: Movie

Regardless of what mappings I use I get the following error:
`[2024-11-20 18:38:11] [Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN89I9RI23BO", Request id "0HN89I9RI23BO:00000001": An unhandled exception was thrown by the application.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/Movies/(500) Days of Summer (2009)'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at Lingarr.Server.Services.SubtitleService.<>c__DisplayClass0_0.<GetAllSubtitles>b__1() in /src/Lingarr.Server/Services/SubtitleService.cs:line 14
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Lingarr.Server.Services.SubtitleService.GetAllSubtitles(String path) in /src/Lingarr.Server/Services/SubtitleService.cs:line 14
   at Lingarr.Server.Services.MediaService.GetMovies(String searchQuery, String orderBy, Boolean ascending, Int32 pageNumber, Int32 pageSize) in /src/Lingarr.Server/Services/MediaService.cs:line 56
   at Lingarr.Server.Controllers.MediaController.GetMovies(String searchQuery, String orderBy, Boolean ascending, Int32 pageSize, Int32 pageNumber) in /src/Lingarr.Server/Controllers/MediaController.cs:line 37
   at lambda_method126(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

**Comment by rowanfuchs** [comment]
Does the sonarr and radarr folders contain a Movies and tv folder? my quick guess is you could try a mapping like:

```
    volumes:
      - /home/dietpi/hdd4tb/Radarr/:/media/Movies
      - /home/dietpi/hdd4tb/Sonarr/:/media/tv
```

**Comment by YaibaToKen** [comment]
Radarr has a root folder called Movies (as defined in their library roots config) and Sonarr has multiple root folders, such as Anime, Cartoons and Series.

**Comment by rowanfuchs** [comment]
Did you try out the volume configuration? What was the result? 
Could you also write out or add a screenshot of the root folder configuration and the `/home/dietpi/hdd4tb/Radarr` and `/home/dietpi/hdd4tb/Sonarr` folder contents

**Comment by YaibaToKen** [comment]
The volume config gave me the same result :/

![image](https://github.com/user-attachments/assets/eee84887-df20-4dcb-a514-282af8f792d2)
![image](https://github.com/user-attachments/assets/c5893779-13ec-41bb-9a64-dde29e70a246)

**Comment by rowanfuchs** [comment]
I see, try this:

```
volumes:
      - /home/dietpi/hdd4tb/Radarr/Movies:/media/Movies
      - /home/dietpi/hdd4tb/Sonarr/Anime:/media/Anime
      - /home/dietpi/hdd4tb/Sonarr/Cartoons:/media/Cartoons
      - /home/dietpi/hdd4tb/Sonarr/Series:/media/Series
```

**Comment by YaibaToKen** [comment]
That worked, thank you
